### ISSUE TITLE
Why orf is not registered as a persistent buffer?

### ISSUE THREAD

**Issue by codars** [r0mainK/reform-outperform#1]
**Question**
In the fast_attention.py, I saw
```
self.register_buffer("orf", create_orf(d_model // h, m), persistent=False)
```
What puzzled me is that `persistent=False` line, which says orf won't be in the state dict of this class. I'm wondering, when you finished training, don't you need to remember the last used orf for inferencing?

**Comment by r0mainK** [comment]
Hey there !

So as you're aware the `orf` matrix is applied to query and keys in order to approximate attention scores between them and compute the whole attention block efficiently, however there is no learning involved with the approximation (for more details on this you can check out the blog post I wrote). The approximation can be done with _any_ random feature matrix, the model will not be tuned to a specific draw. In fact, in the paper they mentionned it helped to redraw the random features periodically during training to smoothe approximation error, as it may be of lesser quality for a given draw.

So yeah in all cases it should not be considered as a parameter, as it can simply be redrawn at inference time - which is why we don't keep it in the state dict. 

If it bothers you can actually check this for yourself: take some query / key / values with a particular structure, like block matrices, and compare the approximation with the real attention, you 'll see the draw doesn't matter, it works all the same.

Anyway hope thi

**Comment by codars** [comment]
Nice explanation! I'll check it myself. Thanks very much! And also thanks for the great blog post!
